Updates `vb` script to handle "multi-box" IDs
Old `vagrant` only stored a single `.vagrant` file.  New `vagrant` has
multiple, easier-to-parse `id` files, even if there's only a single
machine.

diff --git a/bin/vb b/bin/vb
--- a/bin/vb
+++ b/bin/vb
@@ -1,13 +1,23 @@
 #!/bin/sh
 
-if [ ! -f .vagrant ]
+file="$(find .vagrant -maxdepth 0 -type f | grep . || find .vagrant -name id -type f)"
+
+found="$(printf '%s\n' "$file" | grep -c .)"
+if test $found -eq 0
 then
   echo "No .vagrant file found"
   [ -f Vagrantfile ] && echo Try running vagrant up
   exit 1
+elif test $found -gt 1
+then
+  echo "Can't determine which vagrant box to modify"
+  exit 1
 fi
 
-uuid=$(ruby -rjson -e 'puts JSON.parse(File.read(".vagrant"))["active"]["default"]')
+if test $file = '.vagrant'
+then uuid=$(ruby -rjson -e 'puts JSON.parse(File.read(".vagrant"))["active"]["default"]')
+else uuid=$(cat $file)
+fi
 
 case $1 in
   id) printf '%s\n' $uuid ;;
