Rewrite `with-known-host` in Ruby
Mostly just a `nsenter` replacement, but turns out this won't work due
to modern Ruby not being single-threaded.

diff --git a/bin/with-known-host b/bin/with-known-host
--- a/bin/with-known-host
+++ b/bin/with-known-host
@@ -1,58 +1,35 @@
-#!/bin/sh
-set -e
+#!/usr/bin/env ruby
+require 'optparse'
+require 'ostruct'
 
-if test "$_UNSHARED" != 1
-then
-  nsroot=/root/ns
-  nsfile="$nsroot/${*/\//_}"
-  if ! sudo mountpoint "$nsroot"
-  then
-    sudo mkdir -p "$nsroot"
-    sudo mount --bind "$nsroot" "$nsroot"
-    sudo mount --make-private "$nsroot"
-    sudo touch "$nsfile"
-  fi
-  exec sudo unshare --mount="$nsfile" su --session-command 'env _UNSHARED=1 "'"$0"'" "$@"' - $USER -- -- "$(pwd)" "$@"
-fi
+NAMESPACE_TYPES = Dir["/proc/self/ns/*"].map { |f| File.basename(f).to_sym }
 
-test "$_UNSHARED" = 1
-cd "$1"
-shift
+opts = OpenStruct.new(type: nil, pid: nil, file: nil)
+OptionParser.new do |parser|
+  [
+    ['-p', '--pid', '=PID', Integer, 'Other PID'],
+    ['-t', '--type', '=TYPE', NAMESPACE_TYPES, 'Namespace type'],
+    ['-f', '--file', '=FILENAME', String, 'Full namespace filename'],
+  ].each do |spec|
+    setter = spec[1].sub(/^--/,'').sub(/$/,'=').to_sym
+    parser.on(*spec, &opts.method(setter))
+  end
+end.parse!
 
-bound=/mnt/over
-tgt=$HOME/.ssh
-over=$HOME/overlay/$$
-lowerdir=$bound$tgt
+unless opts.file or (opts.pid and opts.type)
+  raise "Must specify either --file or (--pid and --type)"
+end
 
-sudo mount --bind / "$bound"
-mkdir -p "$over"/{u,w}
-sudo mount -t overlay overlay \
-  -o "lowerdir=$lowerdir,upperdir=$over/u,workdir=$over/w" "$tgt"
-cat ~/.ssh/known_hosts > ~/.ssh/known_hosts.$$.orig
+opts.file ||= "/proc/#{opts.pid}/ns/#{opts.type}"
 
-while test $# -gt 0
-do
-  case "$1" in
-    (*=*)
-      new=${1%%=*}
-      orig=${1#*=}
-      host=${new%:*}
-      port=${new#*:}
-      ip=$(dig +short $host)
-
-      if test "$port" = 22
-      then linehost="$host,$ip"
-      else linehost="[$host]:$port,[$ip]:$port"
-      fi
-      ssh-keygen -F "$orig" |
-      awk -v host="$linehost" '/^#/ { next } { $1 = host } 1' |
-      tee -a ~/.ssh/known_hosts
-      ;;
-    (*) break ;;
-  esac
-  shift
-done
-
-test $# -gt 0 || set -- ${SHELL:-/bin/sh}
-stty sane
-"$@"
+begin
+  ns = File::open(opts.file)
+rescue IOError => e
+  warn "Failed to open #{opts.file}: #{e}"
+  exit 1
+end
+syscall 308, ns.fileno, 0
+[opts.pid, 'self', 1].each do |pid|
+  target = File.readlink "/proc/#{pid}/ns/#{opts.type}"
+  puts [target, pid].join(' ')
+end
