Add `uuidstamp` env var for `curl-api-upload-file`
- adds a UUID comment to each uploaded file to ensure uniqueness

E.g.:

```sh
$ photos=( ~/sample-photos/pool/0001.png{,}{,,,,} )
 # photos = ten copies of the same image file
$ curl-api-upload-file $photos
 # uploads 0001.png
 # uploads 0001.png again, which will fail as a dup
 # uploads 0001.png again, which will fail as a dup
 # ...
$ uuidstamp=1 curl-api-upload-file $photos
 # uploads 0001.png with {{uuid1}} as its comment
 # uploads 0001.png with {{uuid2}} as its comment
 # uploads 0001.png with {{uuid3}} as its comment
 # ...
```

diff --git a/.zsh/functions/curl-api-upload-photo b/.zsh/functions/curl-api-upload-photo
--- a/.zsh/functions/curl-api-upload-photo
+++ b/.zsh/functions/curl-api-upload-photo
@@ -1,4 +1,4 @@
-local batch cmd file uuid auth=$(curl-api-file auth)
+local batch cmd file tmpfile uploadfile uuid auth=$(curl-api-file auth)
 local -a cmds
 cmds=( jq s3cmd uuidgen )
 if [[ ! -s $auth ]] ; then warn "Not logged in" ; return 1 ; fi
@@ -16,7 +16,18 @@ s3args=(
 for file ; do
   [[ -z "$batch" ]] && batch=$(curl-api-post /batches | jq -r .id)
   uuid=$(uuidgen)
-  if ! s3cmd $s3args put $file s3://$bucket/$uuid.$file:e ; then
+  if [[ -n "$uuidstamp" ]] ; then
+    if ! tmpfile=`mktemp` ; then
+      warn "Failed to create temp file for uuidstamping"
+      continue
+    fi
+    printf 'uuidstamp %s' "$(uuidgen)" \
+      | convert $file -set comment @- ${file:e}:$tmpfile
+    uploadfile=$tmpfile
+  else
+    uploadfile=$file
+  fi
+  if ! s3cmd $s3args put $uploadfile s3://$bucket/$uuid.$file:e ; then
     warn "Failed to upload $file to S3 (bucket=$bucket)"
     continue
   fi
@@ -24,9 +35,10 @@ for file ; do
     url from-$0 \
     key $uuid.$file:e \
     filename $file:t \
-    size $(stat -c %s $file) \
+    size $(stat -c %s $uploadfile) \
     batch_id $batch \
     | jq -c -r '{"files":.}' \
     | curl-api-post /photos -d @- \
   && echo
+  [[ -n $tmpfile ]] && rm $tmpfile
 done
